-- BASE HISTÓRICA, no ejecutar sobre producción ni usar como seguridad final.
-- La evolución autenticada está en migrations/20260902171856_email_access_control.sql.
-- Este archivo conserva el historial técnico del sitio anterior durante la migración.
create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.service_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique check (char_length(order_number) between 1 and 80),
  service_date date not null default current_date,
  client text not null check (char_length(client) between 1 and 180),
  technician text not null check (char_length(technician) between 1 and 120),
  model text not null check (char_length(model) between 1 and 160),
  observations text not null default '' check (char_length(observations) <= 5000),
  created_at timestamptz not null default now()
);

create table public.spare_parts (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.service_orders(id) on delete cascade,
  code text not null check (char_length(code) between 1 and 100),
  quantity integer not null check (quantity between 1 and 100000),
  description text not null check (char_length(description) between 1 and 500)
);

create index spare_parts_order_id_idx on public.spare_parts(order_id);
create index service_orders_created_at_idx on public.service_orders(created_at desc);
alter table public.service_orders enable row level security;
alter table public.spare_parts enable row level security;
revoke all on public.service_orders, public.spare_parts from anon, authenticated;
create policy "No direct access to service orders" on public.service_orders as restrictive for all to anon, authenticated using (false) with check (false);
create policy "No direct access to spare parts" on public.spare_parts as restrictive for all to anon, authenticated using (false) with check (false);

create table private.app_settings (key text primary key, value text not null);
insert into private.app_settings values ('admin_password_sha256', 'REEMPLAZAR_POR_SHA256');

create function private.submit_service_order(p_order_number text,p_service_date date,p_client text,p_technician text,p_model text,p_observations text,p_parts jsonb) returns uuid
language plpgsql security definer set search_path='' as $$
declare v_order_id uuid; v_count integer;
begin
  if p_parts is null or jsonb_typeof(p_parts)<>'array' then raise exception 'Lista inválida'; end if;
  v_count:=jsonb_array_length(p_parts);
  if v_count<1 or v_count>100 then raise exception 'Debe incluir entre 1 y 100 repuestos'; end if;
  if p_service_date is null then raise exception 'La fecha es obligatoria'; end if;
  insert into public.service_orders(order_number,service_date,client,technician,model,observations) values(trim(p_order_number),p_service_date,trim(p_client),trim(p_technician),trim(p_model),left(coalesce(trim(p_observations),''),5000)) returning id into v_order_id;
  insert into public.spare_parts(order_id,code,quantity,description) select v_order_id,trim(x.code),x.quantity,trim(x.description) from jsonb_to_recordset(p_parts) x(code text,quantity integer,description text);
  if (select count(*) from public.spare_parts where order_id=v_order_id)<>v_count then raise exception 'Repuestos incompletos'; end if;
  return v_order_id;
end $$;

create function private.admin_list_service_orders(p_password text) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_hash text;
begin
  select value into v_hash from private.app_settings where key='admin_password_sha256';
  if v_hash is null or encode(extensions.digest(coalesce(p_password,''),'sha256'),'hex')<>v_hash then raise exception 'Clave incorrecta'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'order_number',o.order_number,'service_date',o.service_date,'client',o.client,'technician',o.technician,'model',o.model,'observations',o.observations,'created_at',o.created_at,'parts',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'code',p.code,'quantity',p.quantity,'description',p.description) order by p.id) from public.spare_parts p where p.order_id=o.id),'[]'::jsonb)) order by o.created_at desc) from public.service_orders o),'[]'::jsonb);
end $$;

create function public.submit_service_order(p_order_number text,p_service_date date,p_client text,p_technician text,p_model text,p_observations text,p_parts jsonb) returns uuid language sql security invoker set search_path='' as $$ select private.submit_service_order(p_order_number,p_service_date,p_client,p_technician,p_model,p_observations,p_parts) $$;
create function public.admin_list_service_orders(p_password text) returns jsonb language sql security invoker set search_path='' as $$ select private.admin_list_service_orders(p_password) $$;
revoke all on function private.submit_service_order(text,date,text,text,text,text,jsonb),private.admin_list_service_orders(text),public.submit_service_order(text,date,text,text,text,text,jsonb),public.admin_list_service_orders(text) from public;
grant usage on schema private to anon,authenticated;
grant execute on function private.submit_service_order(text,date,text,text,text,text,jsonb),private.admin_list_service_orders(text),public.submit_service_order(text,date,text,text,text,text,jsonb),public.admin_list_service_orders(text) to anon,authenticated;
