begin;

create schema if not exists private;
-- Additive staging: preserve the current site's functions and permissions until cutover.
grant usage on schema private to authenticated, supabase_auth_admin;

create table if not exists private.service_access (
  email text primary key check (email = lower(trim(email))),
  role text not null default 'operator' check (role in ('operator','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table private.service_access enable row level security;
revoke all on private.service_access from public, anon, authenticated;
grant select on private.service_access to supabase_auth_admin;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='private' and tablename='service_access' and policyname='auth_hook_can_read_access') then
    create policy auth_hook_can_read_access on private.service_access for select to supabase_auth_admin using (true);
  end if;
end $$;

create table if not exists private.service_password_attempts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  window_start timestamptz not null default now(),
  failures integer not null default 0 check (failures >= 0)
);
alter table private.service_password_attempts enable row level security;
revoke all on private.service_password_attempts from public, anon, authenticated;

create or replace function private.before_service_user_created(event jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
begin
  if not exists (
    select 1 from private.service_access
    where email = lower(trim(event->'user'->>'email')) and active
  ) then
    return jsonb_build_object('error',jsonb_build_object(
      'http_code',403,'message','El correo no está habilitado para este sistema.'));
  end if;
  return '{}'::jsonb;
end $$;
revoke all on function private.before_service_user_created(jsonb) from public, anon, authenticated;
grant execute on function private.before_service_user_created(jsonb) to supabase_auth_admin;

create table if not exists public.service_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique check (char_length(order_number) between 1 and 80),
  service_date date not null default current_date,
  client text not null check (char_length(client) between 1 and 180),
  technician text not null check (char_length(technician) between 1 and 120),
  model text not null check (char_length(model) between 1 and 160),
  observations text not null default '' check (char_length(observations) <= 5000),
  created_at timestamptz not null default now()
);
create table if not exists public.spare_parts (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.service_orders(id) on delete cascade,
  code text not null check (char_length(code) between 1 and 100),
  quantity integer not null check (quantity between 1 and 100000),
  description text not null check (char_length(description) between 1 and 500)
);
alter table public.service_orders add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.service_orders add column if not exists created_by_email text;
create index if not exists spare_parts_order_id_idx on public.spare_parts(order_id);
create index if not exists service_orders_created_at_idx on public.service_orders(created_at desc);
create index if not exists service_orders_created_by_idx on public.service_orders(created_by);
alter table public.service_orders enable row level security;
alter table public.spare_parts enable row level security;
revoke all on public.service_orders, public.spare_parts from public, anon, authenticated;

-- Live database authorization: never trust client-supplied roles or user_metadata.
create or replace function private.service_profile()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare v_profile jsonb;
begin
  if auth.uid() is null then
    raise exception 'Iniciá sesión para continuar.' using errcode = '42501';
  end if;
  select jsonb_build_object('email',a.email,'role',a.role) into v_profile
  from auth.users u join private.service_access a on a.email = lower(u.email)
  where u.id = auth.uid() and u.email_confirmed_at is not null
    and not coalesce(u.is_anonymous,false) and a.active;
  if v_profile is null then
    raise exception 'Tu correo no tiene acceso al sistema.' using errcode = '42501';
  end if;
  return v_profile;
end $$;

create or replace function private.submit_service_order_authenticated(
  p_order_number text,p_service_date date,p_client text,p_technician text,
  p_model text,p_observations text,p_parts jsonb
) returns uuid language plpgsql security definer set search_path = '' as $$
declare v_order_id uuid; v_count integer; v_profile jsonb;
begin
  v_profile := private.service_profile();
  if p_parts is null or jsonb_typeof(p_parts) <> 'array' then raise exception 'Lista de repuestos inválida'; end if;
  v_count := jsonb_array_length(p_parts);
  if v_count < 1 or v_count > 100 then raise exception 'Incluí entre 1 y 100 repuestos'; end if;
  if p_service_date is null then raise exception 'La fecha es obligatoria'; end if;
  insert into public.service_orders(order_number,service_date,client,technician,model,observations,created_by,created_by_email)
  values(trim(p_order_number),p_service_date,trim(p_client),trim(p_technician),trim(p_model),coalesce(trim(p_observations),''),auth.uid(),v_profile->>'email')
  returning id into v_order_id;
  insert into public.spare_parts(order_id,code,quantity,description)
  select v_order_id,trim(x.code),x.quantity,trim(x.description)
  from jsonb_to_recordset(p_parts) x(code text,quantity integer,description text);
  if (select count(*) from public.spare_parts where order_id = v_order_id) <> v_count then raise exception 'Repuestos incompletos'; end if;
  return v_order_id;
end $$;

create or replace function private.list_service_orders(p_password text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_profile jsonb; v_hash text; v_failures integer;
begin
  v_profile := private.service_profile();
  if v_profile->>'role' <> 'admin' then
    if coalesce(p_password,'') = '' then
      return jsonb_build_object('error','Ingresá la clave para consultar y descargar registros.');
    end if;
    insert into private.service_password_attempts(user_id) values(auth.uid()) on conflict do nothing;
    -- Serialize attempts per account; errors are returned, not raised, so counts persist.
    perform 1 from private.service_password_attempts where user_id=auth.uid() for update;
    update private.service_password_attempts set window_start=now(), failures=0
      where user_id=auth.uid() and window_start <= now()-interval '15 minutes';
    select failures into v_failures from private.service_password_attempts where user_id=auth.uid();
    if v_failures >= 5 then
      return jsonb_build_object('error','Demasiados intentos. Esperá 15 minutos para reintentar.');
    end if;
    select value into v_hash from private.app_settings where key='admin_password_sha256';
    if v_hash is null or encode(extensions.digest(p_password,'sha256'),'hex') <> v_hash then
      update private.service_password_attempts set failures=failures+1 where user_id=auth.uid();
      return jsonb_build_object('error','Clave incorrecta.');
    end if;
    update private.service_password_attempts set failures=0 where user_id=auth.uid();
  end if;
  return jsonb_build_object('orders',coalesce((select jsonb_agg(jsonb_build_object(
    'id',o.id,'order_number',o.order_number,'service_date',o.service_date,
    'client',o.client,'technician',o.technician,'model',o.model,'observations',o.observations,
    'created_at',o.created_at,'created_by_email',o.created_by_email,
    'parts',coalesce((select jsonb_agg(jsonb_build_object(
      'id',p.id,'code',p.code,'quantity',p.quantity,'description',p.description
    ) order by p.id) from public.spare_parts p where p.order_id=o.id),'[]'::jsonb)
  ) order by o.created_at desc) from public.service_orders o),'[]'::jsonb));
end $$;

create or replace function public.get_my_service_profile() returns jsonb
language sql security invoker set search_path = '' as $$ select private.service_profile() $$;
create or replace function public.submit_service_order_authenticated(p_order_number text,p_service_date date,p_client text,p_technician text,p_model text,p_observations text,p_parts jsonb)
returns uuid language sql security invoker set search_path = '' as $$ select private.submit_service_order_authenticated(p_order_number,p_service_date,p_client,p_technician,p_model,p_observations,p_parts) $$;
create or replace function public.list_service_orders(p_password text default null) returns jsonb
language sql security invoker set search_path = '' as $$ select private.list_service_orders(p_password) $$;

-- The shared password/hash is preserved. New endpoints additionally require an authorized email.
-- Revoke the legacy anonymous endpoints only after the new login is verified end to end.
revoke all on function private.service_profile(),private.submit_service_order_authenticated(text,date,text,text,text,text,jsonb),private.list_service_orders(text),public.get_my_service_profile(),public.submit_service_order_authenticated(text,date,text,text,text,text,jsonb),public.list_service_orders(text) from public, anon;
grant execute on function private.service_profile(),private.submit_service_order_authenticated(text,date,text,text,text,text,jsonb),private.list_service_orders(text),public.get_my_service_profile(),public.submit_service_order_authenticated(text,date,text,text,text,text,jsonb),public.list_service_orders(text) to authenticated;

notify pgrst, 'reload schema';
commit;
